name: Backend CI
 
on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
    types: [opened, synchronize, reopened, closed]

jobs:
  unit-test:                                    # 단위 테스트를 수행하는 Job (develop 브랜치 PR 대상)
    name: Unit Test
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3              # 소스코드 체크아웃

      - name: Set up JDK 21                    # Java 21 환경 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Grant Gradle permission          # gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Cache Gradle dependencies        # Gradle 캐시로 빌드 속도 향상
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts', 'build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Tests                        # 단위 테스트 실행
        run: ./gradlew test
        
  integration-test:
    name: Integration Test
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Rlatldms!2!3
          MYSQL_DATABASE: leafresh
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --protocol=tcp"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.DOCKER_LOCAL }}" > .env

      - name: Export environment variables
        run: |
          set -o allexport
          source .env
          set +o allexport
          echo "kakao_client_id=${kakao_client_id}"
          echo "jwt_secret=${jwt_secret:0:10}..." # 일부만 출력
      
      - name: Export .env variables to environment
        run: |
          echo "${{ secrets.DOCKER_LOCAL }}" > .env
          grep -v '^#' .env | xargs -L1 echo export >> $GITHUB_ENV
      
      - name: Create GCP credentials file
        run: echo "${{ secrets.GCP_SA_KEY }}" > /home/runner/gcp-sa-key.json

      - name: Build Spring Boot App
        run: ./gradlew bootJar

      - name: Start Spring Boot App with env
        run: |
          source .env
          nohup java \
            -Dspring.profiles.active=$spring_profiles_active \
            -Dspring.datasource.url=jdbc:mysql://${docker_local_db_host}:${db_port}/${docker_local_db_name} \
            -Dspring.datasource.username=${docker_local_db_user} \
            -Dspring.datasource.password=${docker_local_db_password} \
            -Dspring.redis.host=${docker_local_cache_host} \
            -Dspring.redis.port=${docker_local_cache_port} \
            -Djwt.secret="${jwt_secret}" \
            -Dkakao.client-id=${kakao_client_id} \
            -Dkakao.client-secret=${kakao_client_secret} \
            -Dkakao.redirect-uri=${kakao_redirect_uri} \
            -Dai-server.base-url=${ai_server_base_url} \
            -Dgcp.project-id=${gcp_project_id} \
            -Dgcp.credentials.location=${gcp_credentials_location} \
            -jar build/libs/*.jar > app.log 2>&1 &
          echo "✅ Java started, waiting for Spring Boot..."
          
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP > /dev/null; then
              echo "✅ Spring Boot is UP"
              break
            fi
            echo "⏳ Waiting for Spring Boot..."
            sleep 2
          done
      - name: Integration Test
        run: |
          curl -v http://localhost:8080/api/challenges/group/categories || (
            echo "API call failed"
            echo "===== APP.LOG START ====="
            cat app.log || echo "app.log not found"
            echo "===== APP.LOG END ====="
            exit 1
          )
      - name: Stop Spring Boot App
        run: pkill -f 'java -jar'

  build-dev:                                    # develop 브랜치에서 Docker 이미지 빌드 및 푸시
    name: Build and Push Backend Docker (develop only)
    needs: unit-test
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/develop') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'develop')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3              # 소스코드 체크아웃

      - name: Build JAR with Gradle            # JAR 빌드
        run: ./gradlew build

      - name: Set up Docker Buildx             # Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub              # Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image      # Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jchanho99/backend-dev:latest
          cache-from: type=gha,scope=build-backend-dev
          cache-to: type=gha,mode=max,scope=build-backend-dev

  build-prod:                                   # main 브랜치에서 Docker 이미지 빌드 및 푸시
    name: Build and Push Backend Docker (main only)
    needs: integration-test
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3              # 코드 체크아웃

      - name: Set up Docker Buildx             # Docker Buildx 설정
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to Docker Hub              # Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image      # Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jchanho99/backend-prod:latest
          cache-from: type=gha,scope=build-backend-prod
          cache-to: type=gha,mode=max,scope=build-backend-prod

  sync-env-to-secret-manager:
    name: Upload .env to Secret Manager
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_A }}   # 기본값 (main용)
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set GCP Project and Secret Name based on branch
        id: set-env-vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID_A }}" >> $GITHUB_ENV
            echo "SECRET_NAME=env-be-prod" >> $GITHUB_ENV
            echo "${{ secrets.DOCKER_PROD }}" > .env
            echo "Using A project and production .env"
          else
            echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID_B }}" >> $GITHUB_ENV
            echo "SECRET_NAME=env-be-dev" >> $GITHUB_ENV
            echo "${{ secrets.DOCKER_LOCAL }}" > .env
            echo "Using B project and development .env"
          fi

      - name: Activate service account
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project $GCP_PROJECT_ID

      - name: Confirm gcloud authentication
        run: gcloud auth list

      - name: Confirm active gcloud project
        run: gcloud config get-value project

      - name: Validate .env content
        run: |
          if [[ ! -s .env ]]; then
            echo ".env 파일이 비어 있습니다. 종료합니다."
            exit 1
          fi

      - name: Push .env to Secret Manager
        run: |
          if gcloud secrets describe "$SECRET_NAME" >/dev/null 2>&1; then
            echo "Secret $SECRET_NAME exists, adding new version..."
            gcloud secrets versions add "$SECRET_NAME" --data-file=.env
          else
            echo "Secret $SECRET_NAME does not exist, creating..."
            gcloud secrets create "$SECRET_NAME" --data-file=.env --replication-policy=automatic
          fi


